baseURL: "https://unb-mds.github.io/Projeto-P.I.T.E.R/"
languageCode: "pt-br"
title: "P.I.T.E.R - Buscadora de Investimentos em Inteligência Artificial"

# Configurações básicas
disableKinds: ["taxonomy", "term"]
enableRobotsTXT: true
canonifyURLs: false
relativeURLs: true

# Menu de navegação
menu:
  main:
    - name: "Visao Geral"
      url: "/overview/"
      weight: 1
    - name: "Integrantes"
      url: "/integrantes/"
      weight: 2
    - name: "XP"
      url: "/xp/"
      weight: 3
    - name: "Interface"
      url: "/interface/"
      weight: 4
    - name: "MVP"
      url: "/mvp/"
      weight: 5
    - name: "Arquitetura"
      url: "/arquitetura/"
      weight: 6
    - name: "Sprints"
      url: "/sprint/"
      weight: 7
